config/routes.rb
ToddyCatRails::Application.routes.draw do

  # Sign in/out
  get 'login' => 'session#new', as: :login
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy', as: :logout

  # Registration
  get 'register/:code' => 'registration#new', as: :register
  post 'register/:code' => 'registration#create'

  # Reset
  get 'reset/:code' => 'password#edit', as: :reset
  put 'reset/:code' => 'password#update'
  patch 'reset/:code' => 'password#update'

  get 'privacy' => 'site#privacy'
  get 'terms' => 'site#terms'

  root 'site#index'
end

app/models/registrant.rb
class Registrant
	include Mongoid::Document

	field :id, type: String
	field :email, type: String
	field :expires_at, type: Time
end

app/models/user.rb
class User
	include Mongoid::Document
	include Mongoid::Timestamps

	attr_accessor :password, :password_confirmation

	field :id, type: String

	field :name, type: String
	field :email, type: String

	field :salt, type: String
	field :pwd, type: String

	field :code, type: String
	field :expires_at, type: String

	before_save :encrypt_password

	def authenticate(password)
		self.pwd == BCrypt::Engine.hash_secret(password, self.pwd)
	end

	private

	def encrypt_password
		if password.present?
			self.salt = BCrypt::Engine.generate_salt
			self.pwd = BCrypt::Engine.hash_secret(password, self.salt)
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def is_authenticated?
		redirect_to login_url unless current_user
	end

end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
	def edit
		@code = params[:code]
	end

	def update
		
	end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
	def new
		
	end

	def create
		
	end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	before_action :is_authenticated?, only: [:destroy]
	def new
		redirect_to root_url if current_user
	end

	def create
		@user = User.find_by(email: params[:user][:email])

		if @user && @user.authenticate(params[:user][:password])
			session[:user_id] = @user.id
			redirect_to root_url
		else
			render :new, error: "Unable to sign you in. Please try again."
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to login_url, notice: "You've logged out."
	end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

before_action :is_authenticated?, only: [:index]

	def index
		@users = User.all.entries
	end

	def privacy

	end

	def terms

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.slim
.navbar.navbar-inverse.navbar-fixed-top
	.container
		span.navbar-brand.logo ToddyCat

app/views/layouts/_navigation.html.slim
.navbar.navbar-inverse.navbar-fixed-top
	.container
		button type="button" class="navbar-toggle" data-toggle" data-toggle="collapse" data-target=".navbar-collapse"
		span.icon-bar
		span.icon-bar
		span.icon-bar
	= link_to_unless_current "ToddyCat", root_url, class: "navbar-brand logo" do
		span.navbar-brand.logo ToddyCat
		.collapse.navbar-collapse
			ul.nav.navbar-nav.pull-right
				li
					= link_to "Sign Out", logout_url, method: :delete, class: "logout-link"

app/views/layouts/application.html.slim
doctype html
html lang="en"
    head
        meta charset="utf-8"
        meta name="viewport" content="width=device-width, initial-scale-1.0"

        title ToddyCatRails

        = csrf_meta_tags

        = stylesheet_link_tag "application", media: "all"

    body
        #wrap
            - if current_user
                == render partial: 'layouts/navigation'
            - else
                == render partial: 'layouts/header'

            .container
                .page
                    == yield

        #footer
            .container
                p.text-muted.credit
                    => link_to "Privacy Policy", privacy_url
                    ' &bull;
                    => link_to "Terms of Use", terms_url
                    ' &bull; &copy; 2013 ToddyCat

        = javascript_include_tag "application"

app/views/password/edit.html.slim
.row
    .col-lg-4.col-lg-offset-4
        h1 Please choose a new password
        .row
            .col-lg-9
                = form_for :user, url: reset_url, method: :put, html: {role: "form" } do |f|
                    .form-group
                        = f.label :password
                        = f.password_field :password, class: "form-control", placeholder: "Password"
                    .form-group
                        = f.label :password_confirmation
                        = f.password_field :password_confirmation, class: "form-control", placeholder: "Re-type Password"
                    .form-group
                        = token_tag form_authenticity_token
                        => f.submit "Save", class: "btn btn-success"
                        => f.button "Show Passwords", class: "btn btn-warning"

app/views/session/new.html.slim
.row
    .col-lg-4.col-lg-offset-4
        h1 Please sign in
        .row
            .col-lg-9
                = form_for :user, url: login_url, method: "POST", html: {role: "form" } do |f|
                    .form-group
                        = f.label :email
                        = f.text_field :email, class: "form-control", placeholder: "Email address"
                    .form-group
                        = f.label :password
                        = f.password_field :password, class: "form-control", placeholder: "Password"
                    .form-group
                        = token_tag form_authenticity_token
                        => f.submit "Sign In", class: "btn btn-success"
                        => f.button "Show Password", class: "btn btn-warning"

app/views/site/index.html.slim
.row
	.col-lg-6.col-lg-offset-3
		table.table.table-bordered.table-striped
			caption Our users!
			thead
				tr
				th Name
				th Email
				th Created
			tbody
			- @users.each do |user|
				tr
				td #{user.name}
				td #{user.email}
				td #{user.created_at}